import * as T from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
const stage=document.querySelector('#stage');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.setClearColor('#e5ddca');renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;stage.append(renderer.domElement);
const scene=new T.Scene();const camera=new T.PerspectiveCamera(35,1,.1,100);camera.position.set(10,12,15);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.1,0);controls.enableDamping=true;controls.minDistance=5;controls.maxDistance=28;controls.maxPolarAngle=Math.PI*.46;
scene.add(new T.HemisphereLight(0xfff5db,0x727d89,2));const sun=new T.DirectionalLight(0xffecd0,2.5);sun.position.set(-6,12,6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12});sun.shadow.bias=-.0004;scene.add(sun);
const mat=(color,metalness=0,roughness=.7)=>new T.MeshStandardMaterial({color,metalness,roughness});
const gold=mat('#b69045',.65,.35),ivory=mat('#e8d8b2'),blue=mat('#294979',.1,.48),red=mat('#b54832'),wood=mat('#4f5146'),green=mat('#718779'),dark=mat('#303d42');
const board=new T.Group(), cabinet=new T.Group(),ornaments=new T.Group(),inlay=new T.Group(),beads=new T.Group();scene.add(board,cabinet);board.add(ornaments,inlay,beads);beads.visible=false;cabinet.visible=false;
function mesh(g,m,parent,x=0,y=0,z=0){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function cyl(parent,r,h,m,x=0,y=0,z=0,rt=r,n=48){return mesh(new T.CylinderGeometry(rt,r,h,n),m,parent,x,y,z)}
function ball(parent,r,m,x,y,z){return mesh(new T.IcosahedronGeometry(r,2),m,parent,x,y,z)}
function line(parent,pts,m=gold,r=.012){return mesh(new T.TubeGeometry(new T.CatmullRomCurve3(pts.map(p=>new T.Vector3(...p))),Math.max(8,pts.length*4),r,5,false),m,parent)}
function ring(parent,r,y,m=gold,x=0,z=0){const o=mesh(new T.TorusGeometry(r,.012,6,72),m,parent,x,y,z);o.rotation.x=Math.PI/2;return o}
const floor=mesh(new T.PlaneGeometry(200,200),mat('#e5ddca'),scene,0,-.62,0);floor.rotation.x=-Math.PI/2;
cyl(board,6.25,.25,wood,0,-.43,0,6.25,96);cyl(board,6.28,.06,gold,0,-.27,0,6.28,96);cyl(board,6.15,.12,blue,0,-.19,0,6.15,96);
ring(ornaments,5.98,-.118);ring(ornaments,5.8,-.117);
for(let i=0;i<96;i++){const a=i*Math.PI/48;const r=i%4===0?5.63:5.73;line(ornaments,[[Math.cos(a)*r,-.11,Math.sin(a)*r],[Math.cos(a)*5.79,-.11,Math.sin(a)*5.79]],gold,.009)}
const tiles=new Map();const rad=.85;const coords=(q,r)=>[Math.sqrt(3)*rad*(q+r/2),1.5*rad*r];
for(let q=-3;q<=3;q++)for(let r=-3;r<=3;r++){if(Math.abs(q+r)>3)continue;const [x,z]=coords(q,r);const water=r>=2||(q===3&&r>=-1);const h=water?.03:(q<=-2?.43:.22);const col=water?blue:mat(['#91a18b','#a8ac87','#c4bb92','#81998c'][Math.abs(q*3+r*7)%4]);const hex=cyl(board,.824,h+.13,col,x,(h-.13)/2,z,.81,6);hex.rotation.y=0;tiles.set(`${q},${r}`,{x,z,h,water});if(water){for(let j=0;j<3;j++)line(ornaments,[[x-.4,h+.008,z-.28+j*.23],[x-.13,h+.008,z-.23+j*.23],[x+.15,h+.008,z-.28+j*.23],[x+.4,h+.008,z-.24+j*.23]],mat('#759da6',.2),.008)} }
function tree(x,z,h,s=1){cyl(board,.045,.38,wood,x,h+.19,z);for(let i=0;i<3;i++){const o=mesh(new T.ConeGeometry((.25-i*.045)*s,.55*s,7),green,board,x,h+.45+i*.19*s,z);o.rotation.y=i*.5}ball(ornaments,.04,gold,x,h+1.07*s,z)}
for(const key of ['-2,0','-1,-1','0,-2','2,-2','-3,1']){const t=tiles.get(key);tree(t.x-.19,t.z+.12,t.h,.85);tree(t.x+.26,t.z-.18,t.h,.65)}
for(const key of ['-2,-1','-1,-2','1,-3']){const t=tiles.get(key);for(let i=0;i<2;i++){mesh(new T.ConeGeometry(.53-i*.12,1.15-i*.2,5),mat(i?'#d4cdb6':'#a5a691'),board,t.x+i*.35-.12,t.h+.5,t.z+i*.14);mesh(new T.ConeGeometry(.2,.42,5),ivory,board,t.x+i*.35-.12,t.h+.96-i*.08,t.z+i*.14)}}
function piece(parent,x,z,y,color,kind,scale=1){const p=new T.Group();parent.add(p);p.position.set(x,y,z);p.scale.setScalar(scale);cyl(p,.37,.09,gold,0,.045);cyl(p,.32,.12,color,0,.13);cyl(p,.29,.045,ivory,0,.21);const profile=[[.26,.23],[.27,.3],[.22,.44],[.17,.63],[.2,.85],[.14,.96]].map(([a,b])=>new T.Vector2(a,b));mesh(new T.LatheGeometry(profile,12),color,p);ball(p,.145,ivory,0,1.075,0);const nose=mesh(new T.ConeGeometry(.045,.13,4),ivory,p,0,1.065,.15);nose.rotation.x=Math.PI/2;
const deco=new T.Group();p.add(deco);p.userData.deco=deco;
for(let i=0;i<8;i++){const a=i*Math.PI/4;ball(deco,.022,gold,Math.sin(a)*.31,.15,Math.cos(a)*.31);line(deco,[[Math.sin(a)*.245,.32,Math.cos(a)*.245],[Math.sin(a)*.175,.7,Math.cos(a)*.175]],gold,.009)}
if(kind==='king'){cyl(p,.158,.075,gold,0,1.2);for(let i=0;i<7;i++){const a=i*Math.PI*2/7;mesh(new T.ConeGeometry(.045,.14,4),gold,p,Math.sin(a)*.14,1.28,Math.cos(a)*.14)}mesh(new T.SphereGeometry(.23,12,8,0,Math.PI*2,0,Math.PI/2),color,p,0,.92,-.03);cyl(p,.025,.95,gold,.31,.7,.04);ball(p,.075,ivory,.31,1.21,.04)}else{mesh(new T.ConeGeometry(.18,.35,8),ivory,p,0,1.28,0);cyl(p,.022,1.3,gold,.33,.84,0);const halo=mesh(new T.TorusGeometry(.15,.018,6,32),gold,deco,.33,1.57,0);halo.rotation.y=.5;ball(deco,.065,blue,.33,1.57,0)}return p}
const t1=tiles.get('1,0'),t2=tiles.get('-1,1');const figures=[piece(board,t1.x,t1.z,t1.h,blue,'king'),piece(board,t2.x,t2.z,t2.h,red,'sage')];
function city(){const t=tiles.get('0,-1');const p=new T.Group();p.position.set(t.x,t.h,t.z);board.add(p);cyl(p,.65,.12,gold,0,.06,0,.65,8);cyl(p,.57,.15,ivory,0,.18,0,.57,8);for(let i=0;i<8;i++){const a=i*Math.PI/4;const x=Math.sin(a)*.44,z=Math.cos(a)*.44;cyl(p,.064,.55,ivory,x,.52,z);cyl(p,.09,.05,gold,x,.79,z)}cyl(p,.55,.1,ivory,0,.85,0,.55,8);mesh(new T.SphereGeometry(.43,16,8,0,Math.PI*2,0,Math.PI/2),blue,p,0,.9,0);cyl(p,.025,.3,gold,0,1.43);ball(p,.075,gold,0,1.6,0);const a=new T.Group();a.position.set(t.x,t.h+1.65,t.z);ornaments.add(a);for(let i=0;i<3;i++){const o=mesh(new T.TorusGeometry(.31,.012,6,60),gold,a);o.rotation.set(i*.8,.5+i*.8,0)}return a}const celestial=city();
const region=['0,0','1,0','0,-1','1,-1'];const edges=new Map();for(const key of region){const t=tiles.get(key);for(let i=0;i<6;i++){const a=Math.PI/3*i+Math.PI/6;const b=a+Math.PI/3;const p=[t.x+Math.cos(a)*rad,.245,t.z+Math.sin(a)*rad],q=[t.x+Math.cos(b)*rad,.245,t.z+Math.sin(b)*rad];const code=[`${p[0].toFixed(3)},${p[2].toFixed(3)}`,`${q[0].toFixed(3)},${q[2].toFixed(3)}`].sort().join('|');if(edges.has(code))edges.delete(code);else edges.set(code,[p,q])}}
for(const [a,b]of edges.values()){line(inlay,[a,b],gold,.026);ball(inlay,.046,ivory,...a);line(beads,[a,b],dark,.012);for(let i=0;i<9;i++){const v=a.map((n,k)=>n+(b[k]-n)*i/9);ball(beads,.031,i%3===0?gold:blue,...v)}}
const selection=new T.Group();ornaments.add(selection);selection.position.set(t1.x,t1.h+.02,t1.z);ring(selection,.48,0);ring(selection,.54,0);for(let i=0;i<4;i++){const a=i*Math.PI/2;const o=mesh(new T.OctahedronGeometry(.055),gold,selection,Math.cos(a)*.55,.015,Math.sin(a)*.55);o.scale.y=.3}
cyl(cabinet,3.5,.18,wood,0,-.1,0);ring(cabinet,3.3,.005);figures.push(piece(cabinet,-1.1,0,0,blue,'king',2),piece(cabinet,1.1,0,0,red,'sage',2));
let motion=true;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce){motion=false;document.querySelector('#motion').checked=false}
document.querySelector('#motion').onchange=e=>motion=e.target.checked;document.querySelector('#ornament').onchange=e=>{ornaments.visible=e.target.checked;figures.forEach(p=>p.userData.deco.visible=e.target.checked)};
document.querySelectorAll('[data-border]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-border]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));inlay.visible=b.dataset.border==='inlay';beads.visible=!inlay.visible});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const close=b.dataset.view==='pieces';board.visible=!close;cabinet.visible=close;camera.position.set(...(close?[5,5,9]:[10,12,15]));controls.target.set(0,close?1:0,0);document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelector('#note-title').textContent=close?'02 / The pieces':'01 / The world';document.querySelector('#note').textContent=close?'A lacquered sovereign and an ivory augur. Crown, staff and silhouette remain legible; gilt and astronomical details appear up close.':'Terraced ceramic land, engraved enamel seas, and a city conceived as a tiny memory theatre.';});
function resize(){renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(stage);resize();let previous=0;renderer.setAnimationLoop(time=>{const dt=Math.min((time-previous)/1000,.05);previous=time;if(motion){celestial.rotation.y+=dt*.18;selection.rotation.y+=dt*.08}controls.update();renderer.render(scene,camera)});
