// The Codex generator — the whole card pool laid out by theme × channel.
//
// Why this exists (Entry LII, 2026-08-31): the game's content lives in five
// acquisition channels (science / culture / faith / renown / beads) but is
// tagged by FOUR unrelated taxonomies — Orders' `line`, religion's `axis`,
// great people's `family`, beads' `family`+`system` — and wonders, techs,
// rites and governments carry none at all. This script renders that state
// honestly: one section per taxonomy, an Unclaimed section for everything no
// taxonomy owns, and a count table up top. It is the worksheet for unifying
// the theme vocabulary — rerun `npm run codex` after any data edit; never
// hand-edit docs/codex.md.
import { readFileSync, writeFileSync } from 'node:fs';

const load = (f) => JSON.parse(readFileSync(new URL(`../data/${f}.json`, import.meta.url), 'utf8'));
const sc = load('statecraft'), rel = load('religion'), gp = load('greatPeople'),
      beads = load('beads'), bld = load('buildings'), tech = load('techs');

const mark = (row) => row.name
  + (row.retired ? ' (retired)' : '')
  + (row.deferred ? ' †' : '');

// theme -> channel -> [names]; themes namespaced by taxonomy so the four
// vocabularies sit side by side instead of colliding.
const grid = new Map();
const put = (theme, channel, label) => {
  if (!grid.has(theme)) grid.set(theme, new Map());
  const t = grid.get(theme);
  if (!t.has(channel)) t.set(channel, []);
  t.get(channel).push(label);
};
const themeless = (row, field) => !row[field] || row[field] === 'none';

for (const row of Object.values(sc.orders))
  put(themeless(row, 'line') ? 'unclaimed' : `line:${row.line}`, 'culture · Order', mark(row));
for (const row of Object.values(sc.doctrines))
  put(themeless(row, 'line') ? 'unclaimed' : `line:${row.line}`, 'culture · Doctrine', mark(row));
for (const row of Object.values(sc.governments))
  put('unclaimed', 'culture · government', mark(row));
for (const [pool, channel] of [['beliefs', 'faith · pantheon'], ['followerBeliefs', 'faith · follower'], ['enhancerBeliefs', 'faith · enhancer']])
  for (const row of Object.values(rel[pool]))
    put(themeless(row, 'axis') ? 'unclaimed' : `axis:${row.axis}`, channel, mark(row));
for (const row of Object.values(rel.rites))
  put('unclaimed', 'faith · rite', mark(row));
for (const row of Object.values(gp.people))
  put(`family:${row.family}`, `renown · person (Æra ${row.age})`, mark(row));
for (const kind of ['feats', 'endeavours', 'quests', 'reckonings'])
  for (const row of Object.values(beads[kind]))
    put(`bead:${row.family ?? '—'}`, `beads · ${kind.slice(0, -1)}`, mark(row) + (row.system ? ` (${row.system})` : ''));
for (const row of Object.values(bld.buildings))
  if (row.wonder) put('unclaimed', 'science · wonder', mark(row));
for (const row of Object.values(tech.techs))
  if (row.effects?.length) put('unclaimed', 'science · tech effect', mark(row));

const sections = [
  ['The Orders’ lines (`line`)', 'line:'],
  ['Religion’s axes (`axis`)', 'axis:'],
  ['Great-person families (`family`)', 'family:'],
  ['Bead families (`family` + `system`)', 'bead:'],
  ['Unclaimed by any taxonomy', 'unclaimed'],
];
const out = ['# The Codex — the card pool by theme × channel', '',
  '_Generated by `npm run codex`; never hand-edit. One section per **taxonomy** — the point of',
  'this page is that there are four of them plus an unclaimed pile, and unifying them into one',
  'theme vocabulary (Entry LII) is the reorganisation. † marks a deferred row._', ''];
const count = (t) => [...(grid.get(t) ?? new Map()).values()].reduce((n, v) => n + v.length, 0);
out.push('| taxonomy | themes | cards |', '|---|---|---|');
for (const [title, prefix] of sections) {
  const themes = [...grid.keys()].filter((k) => k.startsWith(prefix));
  out.push(`| ${title} | ${prefix === 'unclaimed' ? '—' : themes.length} | ${themes.reduce((n, t) => n + count(t), 0)} |`);
}
out.push('');
for (const [title, prefix] of sections) {
  out.push(`## ${title}`, '');
  const themes = [...grid.keys()].filter((k) => k.startsWith(prefix)).sort((a, b) => count(b) - count(a));
  for (const theme of themes) {
    out.push(`### ${theme.replace(prefix, '') || 'unclaimed'} — ${count(theme)} cards`);
    for (const [channel, names] of [...grid.get(theme)].sort((a, b) => a[0].localeCompare(b[0])))
      out.push(`- **${channel}** (${names.length}): ${names.sort().join(' · ')}`);
    out.push('');
  }
}
writeFileSync(new URL('../docs/codex.md', import.meta.url), out.join('\n'));
console.log('docs/codex.md written:', [...grid.keys()].length, 'themes,',
  [...grid.keys()].reduce((n, t) => n + count(t), 0), 'cards,', count('unclaimed'), 'unclaimed');
