/**
 * Fresh water: lakes, edge rivers, and which tiles can drink.
 *
 * Three passes that run at the end of `generateMap`, in this order, plus the one
 * accessor everything downstream is supposed to read. They live here rather than
 * in `mapgen.ts` because they are a self-contained little geometry library — a
 * flood fill, a corner walk and an adjacency sweep — and because a future
 * "regenerate the rivers only" tool wants them callable on their own.
 *
 * Scope
 * -----
 * This is geography and truth-tracking, deliberately and only. A river costs
 * nothing to cross, a lake grants no bonus, and `Tile.freshwater` is read by
 * nobody yet. Movement effects and the happiness/authority payoffs of fresh
 * water are a later milestone; putting the *fact* on the board first means those
 * rules will not have to invent their own idea of where the water is.
 *
 * Lakes
 * -----
 * A lake is not a terrain the noise field produces — it is a *classification*.
 * After terrain assignment every water tile belongs to some connected water
 * body; the small ones that are not part of the polar ice margin are inland
 * water, and become `lake`. Connectivity is wrap-aware (columns wrap, rows do
 * not), so a puddle straddling the seam is one lake rather than two.
 *
 * Lakes do not mint coast. `coast` is a *marine* terrain — the shallow shelf a
 * trireme hugs — and a pond in the middle of a continent has no shelf. The coast
 * pass in `mapgen.ts` therefore fires only from `ocean`, and because a lake is
 * by definition a water body with no ocean in it, no lake tile is ever adjacent
 * to an ocean tile that could promote it. Lake-adjacent land stays whatever it
 * was; what it gains is `freshwater`, which is the real thing being modelled.
 *
 * Rivers run on edges, not on tiles
 * ---------------------------------
 * See the `map.ts` docblock for the storage convention and the mirror
 * invariant. The *tracing* model is the dual of it: a river is a path along hex
 * **corners**, and each step from one corner to the next crosses exactly one
 * edge, which is the edge the step flags.
 *
 * Corners are named, not searched for. In a pointy-top layout every vertex of
 * the grid is either the north corner or the south corner of exactly one hex —
 * the two families are disjoint, because the north corner of a hex sits 1·size
 * above its centre and no hex centre is 2·size above another. So a corner is
 * `(col, row, north)` with the column wrapped exactly like a tile's, and there
 * are precisely `2 · width · height` of them.
 *
 * The graph is bipartite: every neighbour of a north corner is a south corner
 * and vice versa. For the north corner of H the three neighbours are the south
 * corners of H+NW, H+NE and H+NW+NE (the hex two rows straight up), reached by
 * crossing H's NW edge, H's NE edge, and the east edge of H+NW respectively.
 * `CORNER_STEPS` writes that table down once; the south case is its 180°
 * rotation and is generated by adding 3 to every direction.
 *
 * Descent and the tie-break
 * -------------------------
 * A corner's altitude is the mean elevation of its three hexes. A trace steps to
 * the lowest neighbouring corner whose altitude is **not greater** than the
 * current one, so a river never runs uphill, and ties are broken by the corner's
 * canonical integer key — never by iteration order of a Map or a Set. That
 * matters more than it looks: `elevation` is rank-normalised, so tile values are
 * all distinct *except* on the polar rows, where `polarWaterElevationBonus`
 * clamps a whole plateau to exactly 1. Without the index tie-break, a river born
 * on the ice cap would wander wherever the loop happened to look first.
 *
 * A trace ends when it reaches a corner that touches ocean or lake (a mouth) or
 * a corner that already carries a river (a confluence — the two merge and share
 * the rest of the way down). It fails, and is thrown away whole, if it runs out
 * of downhill before either. A visited set makes loops impossible even across a
 * dead-flat plateau, so every walk terminates.
 *
 * River edges are always between two *land* tiles. That falls out of stopping at
 * the first water-touching corner: the corner before it had three land hexes,
 * and the edge between two corners is shared by two of that corner's hexes.
 */

import { HEX_DIRECTIONS, type Hex } from './hex';
import {
  type GameMap,
  type Tile,
  getTile,
  getTileAt,
  tileHex,
  tileIndex,
  tileNeighbors,
  wrappedDistance,
} from './map';
import { type Rng, shuffle } from './rng';
import { isFreshwaterTerrain, isWaterTerrain } from './terrainData';

/** How many directions a hex has. The width of a `riverEdges` mask. */
export const DIRECTION_COUNT = HEX_DIRECTIONS.length;

/**
 * The direction that points back the way you came.
 *
 * `HEX_DIRECTIONS[d + 3]` is exactly `-HEX_DIRECTIONS[d]` for every `d`, which
 * is what makes the `riverEdges` mirror invariant a plain `+ 3` rather than a
 * lookup table that could drift out of step with the direction list.
 */
export function oppositeDirection(direction: number): number {
  const d = ((direction % DIRECTION_COUNT) + DIRECTION_COUNT) % DIRECTION_COUNT;
  return (d + 3) % DIRECTION_COUNT;
}

/** Does a river run along this tile's edge in `direction`? */
export function hasRiverEdge(tile: Tile, direction: number): boolean {
  return (tile.riverEdges & (1 << direction)) !== 0;
}

/** How many of a tile's six edges carry a river. */
export function riverEdgeCount(tile: Tile): number {
  let count = 0;
  for (let d = 0; d < DIRECTION_COUNT; d++) if (hasRiverEdge(tile, d)) count++;
  return count;
}

/**
 * Flags one edge as a river — on **both** tiles that share it.
 *
 * The only writer of `riverEdges`, which is what keeps the mirror invariant true
 * by construction rather than by discipline. A no-op when the neighbour is off
 * the map (past a pole), because half an edge is not an edge.
 */
export function setRiverEdge(map: GameMap, tile: Tile, direction: number): void {
  const neighbor = neighborInDirection(map, tile, direction);
  if (!neighbor) return;
  tile.riverEdges |= 1 << direction;
  neighbor.riverEdges |= 1 << oppositeDirection(direction);
}

/** The neighbour of a tile in one direction, wrap-aware. `undefined` past a pole. */
export function neighborInDirection(
  map: GameMap,
  tile: Tile,
  direction: number,
): Tile | undefined {
  const d = HEX_DIRECTIONS[direction]!;
  const h = tileHex(tile);
  return getTile(map, { q: h.q + d.q, r: h.r + d.r });
}

// --- fresh water ------------------------------------------------------------

/**
 * Can this tile drink?
 *
 * THE accessor. Nothing outside this module should read `Tile.freshwater`
 * directly: the flag is derived state with an exact definition (see
 * `computeFreshwater`) and the day it grows a second source — an oasis, a
 * marsh — every caller should follow along for free.
 */
export function hasFreshWater(tile: Tile): boolean {
  return tile.freshwater;
}

/**
 * Does this tile touch the sea?
 *
 * `coast` specifically, not "any water": a lake is water a city cannot sail out
 * of, and it already speaks through fresh water. The test is on the neighbours
 * rather than on the tile itself because a city stands on land — the question is
 * whether it can put a harbour on the hex next door.
 *
 * THE coast-adjacency test, and it lives beside `hasFreshWater` because the two
 * are the same question about the other kind of water. It began as a private
 * helper in `render3d/lens3d.ts`, where the settler lens paints a candidate site
 * blue; Milestone 10 prices exactly that site one authority cheaper
 * (`meters.ts`, design ledger Entry I.b), and a discount the board advertises in
 * blue had better be decided by the function that painted it.
 */
export function isCoastal(map: GameMap, tile: Tile): boolean {
  return tileNeighbors(map, tile).some((neighbor) => neighbor.terrain === 'coast');
}

/**
 * Recomputes `Tile.freshwater` for the whole map. Idempotent.
 *
 * A tile has fresh water when it is **land** and either a river runs along one
 * of its own six edges, or one of its six neighbours is a lake. Both halves are
 * deliberate:
 *
 *   · *its own* edges, not a neighbour's — a river two tiles away is somebody
 *     else's water, and because an edge is flagged on both its tiles, "runs
 *     along my border" is already the correct reading of a non-zero mask.
 *   · *lake* neighbours, not water neighbours — the ocean and its coast are
 *     salt. `isFreshwaterTerrain` is the one place that distinction is written.
 *
 * Water tiles are never marked, lakes included. "Which land can drink" is the
 * question; a lake does not drink from itself.
 */
export function computeFreshwater(map: GameMap): void {
  for (const tile of map.tiles) {
    if (isWaterTerrain(tile.terrain)) {
      tile.freshwater = false;
      continue;
    }
    if (tile.riverEdges !== 0) {
      tile.freshwater = true;
      continue;
    }
    tile.freshwater = tileNeighbors(map, tile).some((n) => isFreshwaterTerrain(n.terrain));
  }
}

// --- lakes ------------------------------------------------------------------

/** One connected body of water, as tile indices in ascending order. */
export interface WaterBody {
  tiles: number[];
  /** True when any member sits on row 0 or the last row — the ice margin. */
  touchesPole: boolean;
}

/**
 * Every connected body of water on the map, wrap-aware.
 *
 * Bodies come back in ascending order of their lowest tile index and each body's
 * members are sorted, so the result is a pure function of the map rather than of
 * the order a queue happened to drain.
 */
export function waterBodies(map: GameMap): WaterBody[] {
  const seen = new Uint8Array(map.tiles.length);
  const bodies: WaterBody[] = [];

  for (let start = 0; start < map.tiles.length; start++) {
    if (seen[start]) continue;
    const first = map.tiles[start]!;
    if (!isWaterTerrain(first.terrain)) continue;

    seen[start] = 1;
    const tiles: number[] = [start];
    let touchesPole = first.row === 0 || first.row === map.height - 1;
    // Index-ordered queue: a plain array walked front to back. The membership of
    // a component does not depend on the order, but sorting the output does.
    for (let head = 0; head < tiles.length; head++) {
      const tile = map.tiles[tiles[head]!]!;
      for (const neighbor of tileNeighbors(map, tile)) {
        if (!isWaterTerrain(neighbor.terrain)) continue;
        const index = tileIndex(map, neighbor.col, neighbor.row);
        if (seen[index]) continue;
        seen[index] = 1;
        if (neighbor.row === 0 || neighbor.row === map.height - 1) touchesPole = true;
        tiles.push(index);
      }
    }
    tiles.sort((a, b) => a - b);
    bodies.push({ tiles, touchesPole });
  }
  return bodies;
}

/**
 * Turns small inland water bodies into `lake` terrain. Returns how many became
 * lakes.
 *
 * Two filters, and the polar one is the interesting half. The ice caps are made
 * by pushing the polar rows' elevation up, which leaves ragged little pockets of
 * open water threaded through the ice — geographically those are sea, not
 * ponds, and calling them lakes would sprinkle fresh water across the one part
 * of the map that should be least habitable. Any body with a tile on row 0 or
 * the last row is therefore left as it was, however small.
 *
 * Must run *before* the coast pass, while every water tile is still `ocean`.
 */
export function classifyLakes(map: GameMap, maxSize: number): number {
  let count = 0;
  for (const body of waterBodies(map)) {
    if (body.touchesPole) continue;
    if (body.tiles.length > maxSize) continue;
    for (const index of body.tiles) map.tiles[index]!.terrain = 'lake';
    count++;
  }
  return count;
}

// --- corners ----------------------------------------------------------------

/**
 * A vertex of the hex grid, named as the north or south corner of one hex.
 * `col` is canonical (wrapped); `row` is on the map.
 */
export interface RiverVertex {
  col: number;
  row: number;
  /** North corner of the tile when true, south corner when false. */
  north: boolean;
}

/**
 * The three steps out of a *north* corner, as (hex offset of the far corner's
 * owner, direction of the edge crossed, hex offset of the tile that owns that
 * edge). The south case is this table with 3 added to every direction and every
 * offset negated — see `cornerSteps`.
 *
 * Read it as: from the north corner of H you may go to the south corner of H's
 * NW neighbour (crossing H's own NW edge), the south corner of H's NE neighbour
 * (crossing H's own NE edge), or the south corner of the hex two rows straight
 * up (crossing the east edge of H's NW neighbour).
 */
const NORTH_STEPS: readonly {
  to: Hex;
  /** Which tile owns the edge crossed, relative to the corner's own hex. */
  edgeTile: Hex;
  /** The direction of that edge on that tile. */
  direction: number;
}[] = [
  { to: { q: 0, r: -1 }, edgeTile: { q: 0, r: 0 }, direction: 4 },
  { to: { q: 1, r: -1 }, edgeTile: { q: 0, r: 0 }, direction: 5 },
  { to: { q: 1, r: -2 }, edgeTile: { q: 0, r: -1 }, direction: 0 },
];

/** The three hexes that meet at a corner, relative to the corner's own hex. */
const NORTH_TILES: readonly Hex[] = [
  { q: 0, r: 0 },
  { q: 0, r: -1 },
  { q: 1, r: -1 },
];

function negate(h: Hex): Hex {
  return { q: -h.q, r: -h.r };
}

/** A stable integer key for a corner: `tileIndex * 2` plus the north/south bit. */
export function vertexKey(map: GameMap, v: RiverVertex): number {
  return tileIndex(map, v.col, v.row) * 2 + (v.north ? 0 : 1);
}

/**
 * The three hexes meeting at a corner, or `null` when any of them is off the map.
 *
 * `null` is the answer at the poles, where a corner has only two hexes. Treating
 * those corners as non-existent is what keeps every later step total: a river
 * never has to ask what happens when its altitude is the mean of an unknown
 * number of tiles.
 */
export function vertexTiles(map: GameMap, v: RiverVertex): Tile[] | null {
  const home = getTileAt(map, v.col, v.row);
  if (!home) return null;
  const base = tileHex(home);
  const offsets = v.north ? NORTH_TILES : NORTH_TILES.map(negate);
  const tiles: Tile[] = [];
  for (const offset of offsets) {
    const tile = getTile(map, { q: base.q + offset.q, r: base.r + offset.r });
    if (!tile) return null;
    tiles.push(tile);
  }
  return tiles;
}

/**
 * A corner's altitude: the mean elevation of its three hexes.
 *
 * The mean rather than the minimum because a river follows the *valley*, and the
 * minimum makes the field flat wherever one deep tile is shared by several
 * corners — which is exactly where a trace then stalls.
 */
export function vertexAltitude(map: GameMap, v: RiverVertex): number | null {
  const tiles = vertexTiles(map, v);
  if (!tiles) return null;
  let sum = 0;
  for (const tile of tiles) sum += tile.elevation;
  return sum / tiles.length;
}

export interface CornerStep {
  to: RiverVertex;
  /** The edge crossed, as a tile and one of its six directions. */
  edge: { tile: Tile; direction: number };
}

/**
 * The (up to) three corners reachable from `v`, each with the edge crossed.
 *
 * Steps whose far corner or whose edge tile is off the map are dropped, so the
 * result is 0–3 long. Order is the fixed `NORTH_STEPS` order — deterministic,
 * though every caller re-sorts by altitude anyway.
 */
export function cornerSteps(map: GameMap, v: RiverVertex): CornerStep[] {
  const home = getTileAt(map, v.col, v.row);
  if (!home) return [];
  const base = tileHex(home);
  const steps: CornerStep[] = [];
  for (const step of NORTH_STEPS) {
    const to = v.north ? step.to : negate(step.to);
    const edgeOffset = v.north ? step.edgeTile : negate(step.edgeTile);
    const direction = v.north ? step.direction : oppositeDirection(step.direction);

    const target = getTile(map, { q: base.q + to.q, r: base.r + to.r });
    const edgeTile = getTile(map, { q: base.q + edgeOffset.q, r: base.r + edgeOffset.r });
    if (!target || !edgeTile) continue;
    if (!neighborInDirection(map, edgeTile, direction)) continue;
    steps.push({
      to: { col: target.col, row: target.row, north: !v.north },
      edge: { tile: edgeTile, direction },
    });
  }
  return steps;
}

/** Does any of the three edges meeting at this corner already carry a river? */
export function vertexTouchesRiver(map: GameMap, v: RiverVertex): boolean {
  return cornerSteps(map, v).some((step) => hasRiverEdge(step.edge.tile, step.edge.direction));
}

// --- river tracing ----------------------------------------------------------

export interface RiverConfig {
  /** Rivers per thousand tiles. Scaled by map size; see `riverCountFor`. */
  countPer1000Tiles: number;
  /** Floor on the scaled count, so a duel map is never riverless. */
  minCount: number;
  /** Lowest corner altitude a spring may sit at, on the 0..1 elevation scale. */
  minSpringElevation: number;
  /** Hexes (wrap-aware) two springs must be apart. */
  minSpringSpacing: number;
  /** Traces shorter than this many edges are discarded whole. */
  minLength: number;
  /** Hard cap on a single trace; a walk that hits it is discarded. */
  maxLength: number;
  /** Springs examined before giving up on reaching the target count. */
  maxAttempts: number;
}

/** One traced river. The map keeps only its edges; this is for tests and stats. */
export interface RiverTrace {
  /** The corner path, spring first. Always `edges.length + 1` long. */
  vertices: RiverVertex[];
  /** Edges crossed, in order, as (tile, direction) pairs. */
  edges: { col: number; row: number; direction: number }[];
  /** Why the walk stopped: a mouth, or a confluence with an older river. */
  ending: 'water' | 'river';
}

/** How many rivers a map of this size asks for. */
export function riverCountFor(config: RiverConfig, width: number, height: number): number {
  const scaled = Math.round(((width * height) / 1000) * config.countPer1000Tiles);
  return Math.max(config.minCount, scaled);
}

/**
 * Walks one river down from a spring corner, without writing anything.
 *
 * Returns `null` when the walk ran out of downhill before reaching water or
 * another river, or when it exceeded `maxLength` — a river that goes nowhere is
 * not a short river, it is a mistake, and half of one drawn on the board would
 * read as a canal that stops in a field.
 *
 * Every step goes to the lowest neighbouring corner whose altitude is no greater
 * than the current corner's, ties broken by `vertexKey`. See the module docblock
 * for why the tie-break is load-bearing.
 */
export function traceRiver(
  map: GameMap,
  spring: RiverVertex,
  maxLength: number,
): RiverTrace | null {
  const startAltitude = vertexAltitude(map, spring);
  if (startAltitude === null) return null;

  const vertices: RiverVertex[] = [spring];
  const edges: RiverTrace['edges'] = [];
  const visited = new Set<number>([vertexKey(map, spring)]);

  let current = spring;
  let altitude = startAltitude;

  for (let step = 0; step < maxLength; step++) {
    let best: { step: CornerStep; altitude: number; key: number } | null = null;
    for (const candidate of cornerSteps(map, current)) {
      const key = vertexKey(map, candidate.to);
      if (visited.has(key)) continue;
      const candidateAltitude = vertexAltitude(map, candidate.to);
      if (candidateAltitude === null) continue;
      // Never uphill. Equal is allowed so a river can cross a flat shelf; the
      // visited set is what stops it circling on one.
      if (candidateAltitude > altitude) continue;
      if (
        best === null ||
        candidateAltitude < best.altitude ||
        (candidateAltitude === best.altitude && key < best.key)
      ) {
        best = { step: candidate, altitude: candidateAltitude, key };
      }
    }
    if (!best) return null;

    const { tile, direction } = best.step.edge;
    const mergedHere = hasRiverEdge(tile, direction) || vertexTouchesRiver(map, best.step.to);
    edges.push({ col: tile.col, row: tile.row, direction });
    vertices.push(best.step.to);
    visited.add(best.key);
    current = best.step.to;
    altitude = best.altitude;

    if (mergedHere) return { vertices, edges, ending: 'river' };
    // `current` came through `vertexAltitude`, so its three hexes all exist.
    if ((vertexTiles(map, current) ?? []).some((t) => isWaterTerrain(t.terrain))) {
      return { vertices, edges, ending: 'water' };
    }
  }
  // Ran past the cap without finding the sea. Almost certainly a walk creeping
  // along a plateau; drop it rather than draw it.
  return null;
}

/**
 * Seeds and traces every river on the map, writing the surviving edges.
 *
 * Spring candidates are every corner whose three hexes are all land and whose
 * altitude clears `minSpringElevation`; they are gathered in tile-index order
 * and then shuffled with `rng`, which is the *only* thing the generator rolls
 * dice for. Candidates are tried in that shuffled order until the map has its
 * quota or the attempt budget runs out, skipping any spring too close to one
 * already accepted, and discarding any trace shorter than `minLength`.
 *
 * Order matters and is deliberate: each accepted river's edges are written
 * before the next is traced, so later rivers can — and do — merge into earlier
 * ones. That makes the result depend on the shuffle, which is exactly what the
 * seed is for.
 */
export function traceRivers(map: GameMap, rng: Rng, config: RiverConfig): RiverTrace[] {
  const target = riverCountFor(config, map.width, map.height);

  const candidates: RiverVertex[] = [];
  for (const tile of map.tiles) {
    for (const north of [true, false]) {
      const vertex: RiverVertex = { col: tile.col, row: tile.row, north };
      const tiles = vertexTiles(map, vertex);
      if (!tiles) continue;
      if (tiles.some((t) => isWaterTerrain(t.terrain))) continue;
      let sum = 0;
      for (const t of tiles) sum += t.elevation;
      if (sum / tiles.length < config.minSpringElevation) continue;
      candidates.push(vertex);
    }
  }
  shuffle(rng, candidates);

  const rivers: RiverTrace[] = [];
  const springs: Hex[] = [];
  const attempts = Math.min(candidates.length, config.maxAttempts);
  for (let i = 0; i < attempts && rivers.length < target; i++) {
    const spring = candidates[i]!;
    const hex = tileHex(map.tiles[tileIndex(map, spring.col, spring.row)]!);
    if (springs.some((other) => wrappedDistance(map, hex, other) < config.minSpringSpacing)) {
      continue;
    }
    // A spring standing on an older river would just redraw it from halfway up.
    if (vertexTouchesRiver(map, spring)) continue;
    const trace = traceRiver(map, spring, config.maxLength);
    if (!trace || trace.edges.length < config.minLength) continue;

    for (const edge of trace.edges) {
      const tile = getTileAt(map, edge.col, edge.row);
      if (tile) setRiverEdge(map, tile, edge.direction);
    }
    springs.push(hex);
    rivers.push(trace);
  }
  return rivers;
}
