/**
 * Fresh water: lakes, edge rivers, and which tiles can drink.
 *
 * Three passes that run at the end of `generateMap`, in this order, plus the one
 * accessor everything downstream is supposed to read. They live here rather than
 * in `mapgen.ts` because they are a self-contained little geometry library — a
 * flood fill, a corner walk and an adjacency sweep — and because a future
 * "regenerate the rivers only" tool wants them callable on their own.
 *
 * Scope
 * -----
 * This is geography and truth-tracking, deliberately and only. A river costs
 * nothing to cross, a lake grants no bonus, and `Tile.freshwater` is read by
 * nobody yet. Movement effects and the happiness/authority payoffs of fresh
 * water are a later milestone; putting the *fact* on the board first means those
 * rules will not have to invent their own idea of where the water is.
 *
 * Lakes
 * -----
 * A lake is not a terrain the noise field produces — it is a *classification*.
 * After terrain assignment every water tile belongs to some connected water
 * body; the small ones that are not part of the polar ice margin are inland
 * water, and become `lake`. Connectivity is wrap-aware (columns wrap, rows do
 * not), so a puddle straddling the seam is one lake rather than two.
 *
 * Lakes do not mint coast. `coast` is a *marine* terrain — the shallow shelf a
 * trireme hugs — and a pond in the middle of a continent has no shelf. The coast
 * pass in `mapgen.ts` therefore fires only from `ocean`, and because a lake is
 * by definition a water body with no ocean in it, no lake tile is ever adjacent
 * to an ocean tile that could promote it. Lake-adjacent land stays whatever it
 * was; what it gains is `freshwater`, which is the real thing being modelled.
 *
 * Oases and floodplains
 * ---------------------
 * The two arid-land features are the third and fourth things this module knows
 * about water, and they sit on opposite sides of the same seam. An **oasis** is
 * a *source*: a pool standing on a desert hex, placed with the other features in
 * `mapgen.ts`, which waters itself and its six neighbours. A **floodplain** is a
 * *consequence*: `deriveFloodplains` reads the finished rivers and the placed
 * oases and turns the flat desert they touch into fertile ground, so a map with
 * more rivers grows more of it without anybody tuning a number. Neither rolls a
 * die, and only the oasis appears in `computeFreshwater` — see both docblocks.
 *
 * Rivers run on edges, not on tiles
 * ---------------------------------
 * See the `map.ts` docblock for the storage convention and the mirror
 * invariant. The *tracing* model is the dual of it: a river is a path along hex
 * **corners**, and each step from one corner to the next crosses exactly one
 * edge, which is the edge the step flags.
 *
 * Corners are named, not searched for. In a pointy-top layout every vertex of
 * the grid is either the north corner or the south corner of exactly one hex —
 * the two families are disjoint, because the north corner of a hex sits 1·size
 * above its centre and no hex centre is 2·size above another. So a corner is
 * `(col, row, north)` with the column wrapped exactly like a tile's, and there
 * are precisely `2 · width · height` of them.
 *
 * The graph is bipartite: every neighbour of a north corner is a south corner
 * and vice versa. For the north corner of H the three neighbours are the south
 * corners of H+NW, H+NE and H+NW+NE (the hex two rows straight up), reached by
 * crossing H's NW edge, H's NE edge, and the east edge of H+NW respectively.
 * `CORNER_STEPS` writes that table down once; the south case is its 180°
 * rotation and is generated by adding 3 to every direction.
 *
 * Descent and the tie-break
 * -------------------------
 * A corner's altitude is the mean elevation of its three hexes. A trace steps to
 * the lowest neighbouring corner whose altitude is **not greater** than the
 * current one, so a river never runs uphill, and ties are broken by the corner's
 * canonical integer key — never by iteration order of a Map or a Set. That
 * matters more than it looks: `elevation` is rank-normalised, so tile values are
 * all distinct *except* on the polar rows, where `polarWaterElevationBonus`
 * clamps a whole plateau to exactly 1. Without the index tie-break, a river born
 * on the ice cap would wander wherever the loop happened to look first.
 *
 * A trace ends when it reaches a corner that touches ocean or lake (a mouth) or
 * a corner that already carries a river (a confluence — the two merge and share
 * the rest of the way down). It fails, and is thrown away whole, if it runs out
 * of downhill before either. A visited set makes loops impossible even across a
 * dead-flat plateau, so every walk terminates.
 *
 * River edges are always between two *land* tiles. That falls out of stopping at
 * the first water-touching corner: the corner before it had three land hexes,
 * and the edge between two corners is shared by two of that corner's hexes.
 */

import { HEX_DIRECTIONS, type Hex } from './hex';
import {
  type GameMap,
  type Tile,
  getTile,
  getTileAt,
  tileHex,
  tileIndex,
  tileNeighbors,
  wrappedDistance,
} from './map';
import { type Rng, shuffle } from './rng';
import { isFreshwaterFeature, isFreshwaterTerrain, isWaterTerrain } from './terrainData';

/** How many directions a hex has. The width of a `riverEdges` mask. */
export const DIRECTION_COUNT = HEX_DIRECTIONS.length;

/**
 * The direction that points back the way you came.
 *
 * `HEX_DIRECTIONS[d + 3]` is exactly `-HEX_DIRECTIONS[d]` for every `d`, which
 * is what makes the `riverEdges` mirror invariant a plain `+ 3` rather than a
 * lookup table that could drift out of step with the direction list.
 */
export function oppositeDirection(direction: number): number {
  const d = ((direction % DIRECTION_COUNT) + DIRECTION_COUNT) % DIRECTION_COUNT;
  return (d + 3) % DIRECTION_COUNT;
}

/** Does a river run along this tile's edge in `direction`? */
export function hasRiverEdge(tile: Tile, direction: number): boolean {
  return (tile.riverEdges & (1 << direction)) !== 0;
}

/** How many of a tile's six edges carry a river. */
export function riverEdgeCount(tile: Tile): number {
  let count = 0;
  for (let d = 0; d < DIRECTION_COUNT; d++) if (hasRiverEdge(tile, d)) count++;
  return count;
}

/**
 * Flags one edge as a river — on **both** tiles that share it.
 *
 * The only writer of `riverEdges`, which is what keeps the mirror invariant true
 * by construction rather than by discipline. A no-op when the neighbour is off
 * the map (past a pole), because half an edge is not an edge.
 */
export function setRiverEdge(map: GameMap, tile: Tile, direction: number): void {
  const neighbor = neighborInDirection(map, tile, direction);
  if (!neighbor) return;
  tile.riverEdges |= 1 << direction;
  neighbor.riverEdges |= 1 << oppositeDirection(direction);
}

/** The neighbour of a tile in one direction, wrap-aware. `undefined` past a pole. */
export function neighborInDirection(
  map: GameMap,
  tile: Tile,
  direction: number,
): Tile | undefined {
  const d = HEX_DIRECTIONS[direction]!;
  const h = tileHex(tile);
  return getTile(map, { q: h.q + d.q, r: h.r + d.r });
}

// --- fresh water ------------------------------------------------------------

/**
 * Can this tile drink?
 *
 * THE accessor. Nothing outside this module should read `Tile.freshwater`
 * directly: the flag is derived state with an exact definition (see
 * `computeFreshwater`) and the day it grows a second source every caller should
 * follow along for free.
 *
 * That day was the **oasis**, and the discipline paid: a pool on a desert hex
 * became a source of fresh water by one clause in `computeFreshwater`, and the
 * farm's Feudalism renewal, the settler lens's blue wash and the start scorer's
 * `freshwaterBonus` all learned about it without a line being written in any of
 * them.
 */
export function hasFreshWater(tile: Tile): boolean {
  return tile.freshwater;
}

/**
 * Does this tile touch the sea?
 *
 * `coast` specifically, not "any water": a lake is water a city cannot sail out
 * of, and it already speaks through fresh water. The test is on the neighbours
 * rather than on the tile itself because a city stands on land — the question is
 * whether it can put a harbour on the hex next door.
 *
 * THE coast-adjacency test, and it lives beside `hasFreshWater` because the two
 * are the same question about the other kind of water. It began as a private
 * helper in `render3d/lens3d.ts`, where the settler lens paints a candidate site
 * blue; Milestone 10 prices exactly that site one authority cheaper
 * (`meters.ts`, design ledger Entry I.b), and a discount the board advertises in
 * blue had better be decided by the function that painted it.
 */
export function isCoastal(map: GameMap, tile: Tile): boolean {
  return tileNeighbors(map, tile).some((neighbor) => neighbor.terrain === 'coast');
}

/**
 * Recomputes `Tile.freshwater` for the whole map. Idempotent.
 *
 * A tile has fresh water when it is **land** and any of four things is true: a
 * river runs along one of its own six edges, it is itself an oasis, one of its
 * six neighbours is a lake, or one of them is an oasis. Every clause is
 * deliberate:
 *
 *   · *its own* edges, not a neighbour's — a river two tiles away is somebody
 *     else's water, and because an edge is flagged on both its tiles, "runs
 *     along my border" is already the correct reading of a non-zero mask.
 *   · *lake* neighbours, not water neighbours — the ocean and its coast are
 *     salt. `isFreshwaterTerrain` is the one place that distinction is written.
 *   · an **oasis waters itself**, which no other source here does, and that is
 *     the whole difference between a pool standing on a land hex and a body of
 *     water occupying one. `isFreshwaterFeature` is where that is written down.
 *
 * A **floodplain is not named at all**, and its absence is the point: a
 * floodplain is only ever derived onto ground that already touches a river or an
 * oasis (see `deriveFloodplains`), so it is fresh by construction. Adding a
 * clause for it would be a second rule that could one day disagree with the
 * first — `water.test.ts` asserts the derivation instead.
 *
 * Water tiles are never marked, lakes included. "Which land can drink" is the
 * question; a lake does not drink from itself.
 */
export function computeFreshwater(map: GameMap): void {
  for (const tile of map.tiles) {
    if (isWaterTerrain(tile.terrain)) {
      tile.freshwater = false;
      continue;
    }
    if (tile.riverEdges !== 0 || isFreshwaterFeature(tile.feature)) {
      tile.freshwater = true;
      continue;
    }
    tile.freshwater = tileNeighbors(map, tile).some(
      (n) => isFreshwaterTerrain(n.terrain) || isFreshwaterFeature(n.feature),
    );
  }
}

/**
 * Turns flat desert that touches water into floodplain. Returns how many tiles
 * changed. Idempotent.
 *
 * **Derived, never scattered**, and that is the whole design of the feature: a
 * floodplain is not a thing the generator decides to put somewhere, it is what
 * desert *is* when a river runs through it. So there is no frequency, no share
 * and no dice — the rule is read off the finished water, and a map with more
 * rivers has more floodplain for free.
 *
 * Four conditions, and each one is refusing a hex that would read wrong:
 *
 *   · **desert**, because this is the arid-land feature. A river through
 *     grassland is a river through grassland.
 *   · **flat**, because the yield algebra gives a hill's yield outright over any
 *     feature's (`terrainData.ts`), so a floodplain on a hill would be a name
 *     with no number behind it — and a terraced hillside is not a flood plain.
 *   · **featureless**, so an oasis is never paved over by the pass that reads
 *     it. Nothing else can be standing on desert today; the clause is there for
 *     the day something is.
 *   · **touching a river edge or an oasis**, which is the sentence itself.
 *
 * Runs at **generation only**, after rivers and after the oases, and it must
 * stay that way: `Tile.feature` is one of the two fields that change during play
 * (the chop's), and a pass that re-derived features mid-game would be the map
 * regenerating itself under a save — see CLAUDE.md's traps.
 */
export function deriveFloodplains(map: GameMap): number {
  let count = 0;
  for (const tile of map.tiles) {
    if (tile.terrain !== 'desert' || tile.hills || tile.feature !== 'none') continue;
    const watered =
      tile.riverEdges !== 0 ||
      tileNeighbors(map, tile).some((n) => n.feature === 'oasis');
    if (!watered) continue;
    tile.feature = 'floodplain';
    count++;
  }
  return count;
}

// --- lakes ------------------------------------------------------------------

/** One connected body of water, as tile indices in ascending order. */
export interface WaterBody {
  tiles: number[];
  /** True when any member sits on row 0 or the last row — the ice margin. */
  touchesPole: boolean;
}

/**
 * Every connected body of water on the map, wrap-aware.
 *
 * Bodies come back in ascending order of their lowest tile index and each body's
 * members are sorted, so the result is a pure function of the map rather than of
 * the order a queue happened to drain.
 */
export function waterBodies(map: GameMap): WaterBody[] {
  const seen = new Uint8Array(map.tiles.length);
  const bodies: WaterBody[] = [];

  for (let start = 0; start < map.tiles.length; start++) {
    if (seen[start]) continue;
    const first = map.tiles[start]!;
    if (!isWaterTerrain(first.terrain)) continue;

    seen[start] = 1;
    const tiles: number[] = [start];
    let touchesPole = first.row === 0 || first.row === map.height - 1;
    // Index-ordered queue: a plain array walked front to back. The membership of
    // a component does not depend on the order, but sorting the output does.
    for (let head = 0; head < tiles.length; head++) {
      const tile = map.tiles[tiles[head]!]!;
      for (const neighbor of tileNeighbors(map, tile)) {
        if (!isWaterTerrain(neighbor.terrain)) continue;
        const index = tileIndex(map, neighbor.col, neighbor.row);
        if (seen[index]) continue;
        seen[index] = 1;
        if (neighbor.row === 0 || neighbor.row === map.height - 1) touchesPole = true;
        tiles.push(index);
      }
    }
    tiles.sort((a, b) => a - b);
    bodies.push({ tiles, touchesPole });
  }
  return bodies;
}

/**
 * Turns small inland water bodies into `lake` terrain. Returns how many became
 * lakes.
 *
 * Two filters, and the polar one is the interesting half. The ice caps are made
 * by pushing the polar rows' elevation up, which leaves ragged little pockets of
 * open water threaded through the ice — geographically those are sea, not
 * ponds, and calling them lakes would sprinkle fresh water across the one part
 * of the map that should be least habitable. Any body with a tile on row 0 or
 * the last row is therefore left as it was, however small.
 *
 * Must run *before* the coast pass, while every water tile is still `ocean`.
 */
export function classifyLakes(map: GameMap, maxSize: number): number {
  let count = 0;
  for (const body of waterBodies(map)) {
    if (body.touchesPole) continue;
    if (body.tiles.length > maxSize) continue;
    for (const index of body.tiles) map.tiles[index]!.terrain = 'lake';
    count++;
  }
  return count;
}

// --- landmasses and the shelf ------------------------------------------------

/**
 * Connected land, wrap-aware: tile index → landmass id, `-1` on water.
 *
 * Seeded in tile-index order, so a landmass's id is a fact about the map rather
 * than about the order a traversal happened to run — which is what lets a
 * continent's number be printed and compared. Ids ascend with the lowest member
 * tile index, so landmass 0 always contains the map's first land tile.
 *
 * Lives here rather than beside its oldest caller (`carveContinents`,
 * `resources.ts`) because it is a fact about which hexes are sea, and because
 * three modules on either side of that one now need it: `resources.ts` still
 * re-exports the name it always had, `startPositions.ts` asks it for the
 * landmass floor, and `mapgen.ts` asks it for the shelf chains below. `water.ts`
 * is a leaf — `hex`, `map`, `rng`, `terrainData` and nothing else — so every one
 * of them can import it without closing a load-time cycle.
 */
export function landRegions(map: GameMap): Int32Array {
  const regions = new Int32Array(map.tiles.length).fill(-1);
  let next = 0;
  for (const seed of map.tiles) {
    if (isWaterTerrain(seed.terrain)) continue;
    const seedIndex = tileIndex(map, seed.col, seed.row);
    if (regions[seedIndex] !== -1) continue;
    const id = next++;
    regions[seedIndex] = id;
    const frontier: Tile[] = [seed];
    while (frontier.length > 0) {
      const from = frontier.pop()!;
      for (const near of tileNeighbors(map, from)) {
        if (isWaterTerrain(near.terrain)) continue;
        const index = tileIndex(map, near.col, near.row);
        if (regions[index] !== -1) continue;
        regions[index] = id;
        frontier.push(near);
      }
    }
  }
  return regions;
}

/**
 * How much land stands on each tile's own landmass. `0` on water.
 *
 * The reading "is this hex somewhere a civilisation could live", asked of the
 * map and not of the neighbourhood — see `StartsConfig.minLandmassShare`.
 */
export function landmassSizes(map: GameMap): Int32Array {
  const regions = landRegions(map);
  let count = 0;
  for (const id of regions) if (id + 1 > count) count = id + 1;
  const size = new Int32Array(count);
  for (const id of regions) if (id >= 0) size[id]! += 1;
  const out = new Int32Array(map.tiles.length);
  for (let i = 0; i < regions.length; i++) {
    const id = regions[i]!;
    out[i] = id < 0 ? 0 : size[id]!;
  }
  return out;
}

/** Land, or the shelf a coastal hull may sail — the graph a shelf chain walks. */
function onTheShelf(tile: Tile): boolean {
  return tile.terrain === 'coast' || !isWaterTerrain(tile.terrain);
}

/**
 * Everything the mainland can reach without ever leaving the shelf.
 *
 * A multi-source flood from `sources` over tiles that are land or `coast`, which
 * is exactly the set of hexes an embarked settler or a coastal hull may stand
 * on. Deep ocean and lakes stop it.
 */
function shelfReach(map: GameMap, sources: readonly number[]): Uint8Array {
  const seen = new Uint8Array(map.tiles.length);
  const queue: number[] = [];
  for (const index of sources) {
    if (seen[index]) continue;
    seen[index] = 1;
    queue.push(index);
  }
  for (let head = 0; head < queue.length; head++) {
    for (const near of tileNeighbors(map, map.tiles[queue[head]!]!)) {
      const index = tileIndex(map, near.col, near.row);
      if (seen[index] || !onTheShelf(near)) continue;
      seen[index] = 1;
      queue.push(index);
    }
  }
  return seen;
}

/**
 * Joins every island to the mainland's shelf, by promoting the ocean between
 * them to `coast`. Returns how many hexes of ocean became shelf.
 *
 * The second half of the pangaea ruling (2026-09-03): an island the player can
 * *see* and cannot *sail to* is worse than no island at all, because this game
 * ends before ocean-going hulls exist. `coast.rings` already grows a two-hex
 * shelf off every shore, so an island within four hexes of the mainland is
 * joined for free; this pass is for the ones that are not, and it is what turns
 * "islands usually reachable" into a guarantee the tests can hold.
 *
 * **It moves no land.** A land bridge would change the land fraction, the
 * terrain census and every density budget counted per land tile; a *shelf* is
 * the same continental shelf real islands sit on, costs the map nothing but a
 * ribbon of shallow water, and is exactly the thing being promised — that a
 * coastal hull can get there. The one thing it does widen is the pool of tiles a
 * sea resource may land on, which the 8/27 note wanted anyway.
 *
 * Deterministic without dice: landmasses are numbered in tile-index order, they
 * are joined in that order, and each bridge is the BFS-shortest ocean path from
 * the island to the shelf — with the queue seeded and drained in tile-index
 * order, so among equally short paths the same one is chosen every time.
 *
 * Runs after the coast pass and before the rivers, so it costs the rng stream
 * nothing and every later pass reads a finished shelf.
 */
export function chainIslandShelves(map: GameMap): number {
  const regions = landRegions(map);
  const members: number[][] = [];
  for (let i = 0; i < regions.length; i++) {
    const id = regions[i]!;
    if (id < 0) continue;
    (members[id] ??= []).push(i);
  }
  if (members.length <= 1) return 0;

  // The mainland is the largest landmass, ties by lowest member tile index —
  // which is the id order, so a plain `>` over ids ascending picks the first.
  let mainland = 0;
  for (let id = 1; id < members.length; id++) {
    if (members[id]!.length > members[mainland]!.length) mainland = id;
  }

  let paved = 0;
  let reach = shelfReach(map, members[mainland]!);
  for (let id = 0; id < members.length; id++) {
    if (id === mainland) continue;
    // A previous bridge may have swept this island in already — an island chain
    // is joined by one ribbon, not by one ribbon per island.
    if (reach[members[id]![0]!]) continue;

    // Shortest way out across open ocean. The sources are the island's *own*
    // shelf — its land and the two rings of coast pass 3 already gave it —
    // because that is where a hull setting out from the island actually starts;
    // seeding from the land alone would leave the walk unable to take its first
    // step, its own shelf not being ocean. From there it steps through `ocean`
    // only (never a lake, never somebody else's land) and stops the moment it
    // touches the mainland's shelf.
    const shore = shelfReach(map, members[id]!);
    const from = new Int32Array(map.tiles.length).fill(-1);
    const queue: number[] = [];
    for (let index = 0; index < shore.length; index++) {
      if (!shore[index]) continue;
      from[index] = index;
      queue.push(index);
    }
    let landed = -1;
    for (let head = 0; head < queue.length && landed < 0; head++) {
      for (const near of tileNeighbors(map, map.tiles[queue[head]!]!)) {
        const index = tileIndex(map, near.col, near.row);
        if (from[index]! >= 0) continue;
        if (reach[index]) {
          from[index] = queue[head]!;
          landed = index;
          break;
        }
        if (near.terrain !== 'ocean') continue;
        from[index] = queue[head]!;
        queue.push(index);
      }
    }
    // No way through at all — an island ringed by lake, or a map with no ocean.
    // Leaving it alone is the honest outcome; nothing here may invent water.
    if (landed < 0) continue;

    for (let at = from[landed]!; !shore[at]; at = from[at]!) {
      map.tiles[at]!.terrain = 'coast';
      paved += 1;
    }
    reach = shelfReach(map, members[mainland]!);
  }
  return paved;
}

// --- corners ----------------------------------------------------------------

/**
 * A vertex of the hex grid, named as the north or south corner of one hex.
 * `col` is canonical (wrapped); `row` is on the map.
 */
export interface RiverVertex {
  col: number;
  row: number;
  /** North corner of the tile when true, south corner when false. */
  north: boolean;
}

/**
 * The three steps out of a *north* corner, as (hex offset of the far corner's
 * owner, direction of the edge crossed, hex offset of the tile that owns that
 * edge). The south case is this table with 3 added to every direction and every
 * offset negated — see `cornerSteps`.
 *
 * Read it as: from the north corner of H you may go to the south corner of H's
 * NW neighbour (crossing H's own NW edge), the south corner of H's NE neighbour
 * (crossing H's own NE edge), or the south corner of the hex two rows straight
 * up (crossing the east edge of H's NW neighbour).
 */
const NORTH_STEPS: readonly {
  to: Hex;
  /** Which tile owns the edge crossed, relative to the corner's own hex. */
  edgeTile: Hex;
  /** The direction of that edge on that tile. */
  direction: number;
}[] = [
  { to: { q: 0, r: -1 }, edgeTile: { q: 0, r: 0 }, direction: 4 },
  { to: { q: 1, r: -1 }, edgeTile: { q: 0, r: 0 }, direction: 5 },
  { to: { q: 1, r: -2 }, edgeTile: { q: 0, r: -1 }, direction: 0 },
];

/** The three hexes that meet at a corner, relative to the corner's own hex. */
const NORTH_TILES: readonly Hex[] = [
  { q: 0, r: 0 },
  { q: 0, r: -1 },
  { q: 1, r: -1 },
];

function negate(h: Hex): Hex {
  return { q: -h.q, r: -h.r };
}

/** A stable integer key for a corner: `tileIndex * 2` plus the north/south bit. */
export function vertexKey(map: GameMap, v: RiverVertex): number {
  return tileIndex(map, v.col, v.row) * 2 + (v.north ? 0 : 1);
}

/**
 * The three hexes meeting at a corner, or `null` when any of them is off the map.
 *
 * `null` is the answer at the poles, where a corner has only two hexes. Treating
 * those corners as non-existent is what keeps every later step total: a river
 * never has to ask what happens when its altitude is the mean of an unknown
 * number of tiles.
 */
export function vertexTiles(map: GameMap, v: RiverVertex): Tile[] | null {
  const home = getTileAt(map, v.col, v.row);
  if (!home) return null;
  const base = tileHex(home);
  const offsets = v.north ? NORTH_TILES : NORTH_TILES.map(negate);
  const tiles: Tile[] = [];
  for (const offset of offsets) {
    const tile = getTile(map, { q: base.q + offset.q, r: base.r + offset.r });
    if (!tile) return null;
    tiles.push(tile);
  }
  return tiles;
}

/**
 * A corner's altitude: the mean elevation of its three hexes.
 *
 * The mean rather than the minimum because a river follows the *valley*, and the
 * minimum makes the field flat wherever one deep tile is shared by several
 * corners — which is exactly where a trace then stalls.
 */
export function vertexAltitude(map: GameMap, v: RiverVertex): number | null {
  const tiles = vertexTiles(map, v);
  if (!tiles) return null;
  let sum = 0;
  for (const tile of tiles) sum += tile.elevation;
  return sum / tiles.length;
}

export interface CornerStep {
  to: RiverVertex;
  /** The edge crossed, as a tile and one of its six directions. */
  edge: { tile: Tile; direction: number };
}

/**
 * The (up to) three corners reachable from `v`, each with the edge crossed.
 *
 * Steps whose far corner or whose edge tile is off the map are dropped, so the
 * result is 0–3 long. Order is the fixed `NORTH_STEPS` order — deterministic,
 * though every caller re-sorts by altitude anyway.
 */
export function cornerSteps(map: GameMap, v: RiverVertex): CornerStep[] {
  const home = getTileAt(map, v.col, v.row);
  if (!home) return [];
  const base = tileHex(home);
  const steps: CornerStep[] = [];
  for (const step of NORTH_STEPS) {
    const to = v.north ? step.to : negate(step.to);
    const edgeOffset = v.north ? step.edgeTile : negate(step.edgeTile);
    const direction = v.north ? step.direction : oppositeDirection(step.direction);

    const target = getTile(map, { q: base.q + to.q, r: base.r + to.r });
    const edgeTile = getTile(map, { q: base.q + edgeOffset.q, r: base.r + edgeOffset.r });
    if (!target || !edgeTile) continue;
    if (!neighborInDirection(map, edgeTile, direction)) continue;
    steps.push({
      to: { col: target.col, row: target.row, north: !v.north },
      edge: { tile: edgeTile, direction },
    });
  }
  return steps;
}

/** Does any of the three edges meeting at this corner already carry a river? */
export function vertexTouchesRiver(map: GameMap, v: RiverVertex): boolean {
  return cornerSteps(map, v).some((step) => hasRiverEdge(step.edge.tile, step.edge.direction));
}

// --- river tracing ----------------------------------------------------------

export interface RiverConfig {
  /** Rivers per thousand tiles. Scaled by map size; see `riverCountFor`. */
  countPer1000Tiles: number;
  /** Floor on the scaled count, so a duel map is never riverless. */
  minCount: number;
  /** Lowest corner altitude a spring may sit at, on the 0..1 elevation scale. */
  minSpringElevation: number;
  /**
   * Hexes (wrap-aware) two springs must be apart.
   *
   * 1, which is to say "not the same hex", and that is a deliberate setting
   * rather than a disabled rule. Springs now have to stand on range ground, and
   * range ground is a fifth of the land gathered into lines — spread them out
   * on top of that and the biggest maps simply cannot seat their own river
   * quota. Nothing is lost by letting two springs share a ridge: a trace that
   * runs into an existing river merges with it (`ending: 'river'`), so what
   * close springs make is a river *system* with tributaries, which is what a
   * mountain range should shed. A spring standing *on* an existing river is
   * refused separately, by `vertexTouchesRiver`.
   */
  minSpringSpacing: number;
  /** Traces shorter than this many edges are discarded whole. */
  minLength: number;
  /** Hard cap on a single trace; a walk that hits it is discarded. */
  maxLength: number;
  /**
   * How many times one trace may back up to its last fork and take the next way
   * down before it is abandoned. **Trace persistence.**
   *
   * 0 is the plain greedy walk this began as — always the lowest step, and the
   * first corner with no way down kills the river — and it is still the default
   * of `traceRiver`, so the knob is opt-in rather than a behaviour change hiding
   * in a signature.
   *
   * It is worth a number of its own because the greedy walk *was the binding
   * constraint on how many rivers a map has*. Measured over ten standard seeds:
   * 989 spring corners clear `minSpringElevation`, every one of them was tried,
   * and 55% of the traces died in a local pit of the corner field — so the quota
   * could be raised as high as anybody liked and the map still came back with
   * twenty-nine rivers. A pit is not a statement about the geography; it is an
   * artefact of reading a valley off the mean of three ranked hexes, and the
   * valley usually continues one fork back.
   *
   * Nothing about descent is relaxed to buy that. Every step of the surviving
   * path is still to a corner no higher than the one before it — backtracking
   * only ever *unsays* a step and takes the next-lowest alternative at that same
   * fork, so the invariant is a property of the path rather than a promise the
   * search makes.
   */
  backtrackSteps: number;
  /**
   * Springs examined per river the map asks for.
   *
   * Per river rather than a flat cap, because the budget has to grow with the
   * quota it is a budget *for*. A flat 600 was enough while a spring could sit
   * anywhere in the top third of the land; once springs are range ground — a
   * fifth of the land, gathered into lines — a giant map wanted its 141 rivers
   * out of a budget that ran out around the ninetieth, and simply came up
   * short. A per-river budget is the same number on every size.
   */
  attemptsPerRiver: number;
}

/** One traced river. The map keeps only its edges; this is for tests and stats. */
export interface RiverTrace {
  /** The corner path, spring first. Always `edges.length + 1` long. */
  vertices: RiverVertex[];
  /** Edges crossed, in order, as (tile, direction) pairs. */
  edges: { col: number; row: number; direction: number }[];
  /** Why the walk stopped: a mouth, or a confluence with an older river. */
  ending: 'water' | 'river';
}

/** How many rivers a map of this size asks for. */
export function riverCountFor(config: RiverConfig, width: number, height: number): number {
  const scaled = Math.round(((width * height) / 1000) * config.countPer1000Tiles);
  return Math.max(config.minCount, scaled);
}

/**
 * The ways down out of one corner, lowest first, ties by `vertexKey`.
 *
 * Split out of the walk because the walk now needs the *list* rather than the
 * best of it: a trace that has to back up wants the next way down at the fork it
 * came from, and "next" is only a word if the order was written somewhere. The
 * order is the same one the greedy walk implied — see the module docblock for
 * why the tie-break on the key is load-bearing rather than tidy.
 *
 * Steps that run uphill are not in the list at all. Equal altitude is, so a
 * river can cross a flat shelf; the caller's visited set is what stops it
 * circling on one.
 */
function waysDown(
  map: GameMap,
  from: RiverVertex,
  altitude: number,
): { step: CornerStep; altitude: number; key: number }[] {
  const options: { step: CornerStep; altitude: number; key: number }[] = [];
  for (const candidate of cornerSteps(map, from)) {
    const candidateAltitude = vertexAltitude(map, candidate.to);
    if (candidateAltitude === null) continue;
    if (candidateAltitude > altitude) continue;
    options.push({ step: candidate, altitude: candidateAltitude, key: vertexKey(map, candidate.to) });
  }
  options.sort((a, b) => a.altitude - b.altitude || a.key - b.key);
  return options;
}

/** One corner on the walk's current path, and how far through its forks it is. */
interface TraceFrame {
  vertex: RiverVertex;
  altitude: number;
  options: { step: CornerStep; altitude: number; key: number }[];
  /** Index of the next fork to try. Equal to `options.length` when spent. */
  next: number;
}

/**
 * Walks one river down from a spring corner, without writing anything.
 *
 * Returns `null` when the walk ran out of downhill before reaching water or
 * another river, or when it exceeded `maxLength` — a river that goes nowhere is
 * not a short river, it is a mistake, and half of one drawn on the board would
 * read as a canal that stops in a field.
 *
 * Every step goes to the lowest neighbouring corner whose altitude is no greater
 * than the current corner's, ties broken by `vertexKey`. See the module docblock
 * for why the tie-break is load-bearing.
 *
 * Backtracking
 * ------------
 * `backtracks` is how many times the walk may **unsay a step** — pop back to the
 * fork it came from and take the next way down there — before it gives up. At
 * **0**, the default, this is exactly the greedy walk it has always been: the
 * first corner with nothing below it kills the river. See
 * `RiverConfig.backtrackSteps` for why the number exists and what it bought.
 *
 * The search is a depth-first walk of the corner graph with that pop budget, and
 * the two things worth saying about it are both about what it does *not* relax:
 *
 *   · every corner on the emitted path is strictly no higher than the one before
 *     it, because `waysDown` never returns an uphill fork. Backtracking removes
 *     steps; it never adds one the greedy walk would have refused.
 *   · a corner is marked visited on the way in and **unmarked on the way back
 *     out**, so the path is always simple while a branch that failed leaves
 *     nothing behind for the branch that replaces it. Loops remain impossible.
 *
 * Deterministic: the fork order is total (altitude, then key) and the budget is
 * a count, so the same spring on the same board walks the same way every time.
 */
export function traceRiver(
  map: GameMap,
  spring: RiverVertex,
  maxLength: number,
  backtracks = 0,
): RiverTrace | null {
  const startAltitude = vertexAltitude(map, spring);
  if (startAltitude === null) return null;

  const vertices: RiverVertex[] = [spring];
  const edges: RiverTrace['edges'] = [];
  const visited = new Set<number>([vertexKey(map, spring)]);
  const stack: TraceFrame[] = [
    { vertex: spring, altitude: startAltitude, options: waysDown(map, spring, startAltitude), next: 0 },
  ];
  let budget = Math.max(0, Math.round(backtracks));

  while (stack.length > 0) {
    const frame = stack[stack.length - 1]!;
    // Spent forks, or a branch that has run past the cap without finding the
    // sea — almost certainly a walk creeping along a plateau. Either way this
    // corner has nothing left to offer, so back out of it if the budget allows.
    if (frame.next >= frame.options.length || edges.length >= maxLength) {
      if (budget === 0 || stack.length === 1) return null;
      budget -= 1;
      visited.delete(vertexKey(map, frame.vertex));
      stack.pop();
      vertices.pop();
      edges.pop();
      continue;
    }

    const option = frame.options[frame.next]!;
    frame.next += 1;
    if (visited.has(option.key)) continue;

    const { tile, direction } = option.step.edge;
    const mergedHere = hasRiverEdge(tile, direction) || vertexTouchesRiver(map, option.step.to);
    edges.push({ col: tile.col, row: tile.row, direction });
    vertices.push(option.step.to);
    visited.add(option.key);

    if (mergedHere) return { vertices, edges, ending: 'river' };
    // `option.step.to` came through `vertexAltitude`, so its three hexes exist.
    if ((vertexTiles(map, option.step.to) ?? []).some((t) => isWaterTerrain(t.terrain))) {
      return { vertices, edges, ending: 'water' };
    }
    stack.push({
      vertex: option.step.to,
      altitude: option.altitude,
      options: waysDown(map, option.step.to, option.altitude),
      next: 0,
    });
  }
  // Unreachable: the loop returns rather than emptying the stack, because the
  // spring frame refuses to be popped. Said out loud so the exit is total.
  return null;
}

/**
 * Seeds and traces every river on the map, writing the surviving edges.
 *
 * Spring candidates are every corner whose three hexes are all land and whose
 * altitude clears `minSpringElevation`; they are gathered in tile-index order
 * and then shuffled with `rng`, which is the *only* thing the generator rolls
 * dice for. Candidates are tried in that shuffled order until the map has its
 * quota or the attempt budget runs out, skipping any spring too close to one
 * already accepted, and discarding any trace shorter than `minLength`.
 *
 * Order matters and is deliberate: each accepted river's edges are written
 * before the next is traced, so later rivers can — and do — merge into earlier
 * ones. That makes the result depend on the shuffle, which is exactly what the
 * seed is for.
 */
export function traceRivers(map: GameMap, rng: Rng, config: RiverConfig): RiverTrace[] {
  const target = riverCountFor(config, map.width, map.height);

  const candidates: RiverVertex[] = [];
  for (const tile of map.tiles) {
    for (const north of [true, false]) {
      const vertex: RiverVertex = { col: tile.col, row: tile.row, north };
      const tiles = vertexTiles(map, vertex);
      if (!tiles) continue;
      if (tiles.some((t) => isWaterTerrain(t.terrain))) continue;
      let sum = 0;
      for (const t of tiles) sum += t.elevation;
      if (sum / tiles.length < config.minSpringElevation) continue;
      candidates.push(vertex);
    }
  }
  shuffle(rng, candidates);

  const rivers: RiverTrace[] = [];
  const springs: Hex[] = [];
  const attempts = Math.min(candidates.length, target * config.attemptsPerRiver);
  for (let i = 0; i < attempts && rivers.length < target; i++) {
    const spring = candidates[i]!;
    const hex = tileHex(map.tiles[tileIndex(map, spring.col, spring.row)]!);
    if (springs.some((other) => wrappedDistance(map, hex, other) < config.minSpringSpacing)) {
      continue;
    }
    // A spring standing on an older river would just redraw it from halfway up.
    if (vertexTouchesRiver(map, spring)) continue;
    const trace = traceRiver(map, spring, config.maxLength, config.backtrackSteps);
    if (!trace || trace.edges.length < config.minLength) continue;

    for (const edge of trace.edges) {
      const tile = getTileAt(map, edge.col, edge.row);
      if (tile) setRiverEdge(map, tile, edge.direction);
    }
    springs.push(hex);
    rivers.push(trace);
  }
  return rivers;
}
